services:
  mysql:
    image: mysql
    environment:
      - MYSQL_USER=${USERNAME}
      - MYSQL_DATABASE=${DATABASE}
      - MYSQL_PASSWORD=${PASSWORD}
      - MYSQL_ROOT_PASSWORD=${PASSWORD_ROOT}
    volumes:
      - ./mysql:/var/lib/mysql
      - ./datos.sql:/docker-entrypoint-initdb.d/datos.sql
    ports:
      - ${PORT}:3306
    container_name: mysql
  phpmyadmin:
    image: phpmyadmin
    ports:
      - 8100:80
    environment:
      - PMA_HOST=mysql


